apiVersion: v1
kind: ConfigMap
metadata:
  name: txtdirect
  namespace: kubecon
  labels:
    app: txtdirect
data:
  Caddyfile: |
    # TXTDirect -> CoreDNS gateway
    :8080 {
      tls off
      txtdirect {
        enable host
        resolver 127.0.0.1:53
      }
      prometheus
      errors
    }
    :80/healthz {
      tls off
      status 200 /
    }
    :80/probez {
      tls off
      status 200 /
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-k8s
  namespace: kubecon
  labels:
    app: txtdirect
data:
  Corefile: |
    .:53 {
      errors
      health :8081
      prometheus :9153
      forward . 10.55.240.23
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-ds
  namespace: kubecon
  labels:
    app: txtdirect
data:
  Corefile: |
    .:53 {
      errors
      health :8081
      prometheus :9153
      # forward IP from DS needs to be manually set to the DS running on the same node!
      forward . 10.52.7.216
    }
