apiVersion: v1
kind: ConfigMap
metadata:
  name: txtdirect
  namespace: kubecon
  labels:
    app: txtdirect
data:
  caddyfile: |
    # TXTDirect -> CoreDNS k8s
    :8001 {
      tls off
      txtdirect {
        enable host
        resolver -DNSIP-:53
      }
      prometheus
      log / stdout "{remote} - [{when_iso}] \"{method} {uri} {proto}\" {status} {size} {latency}"
      errors
    }
    # TXTDirect -> CoreDNS local
    :8002 {
      tls off
      txtdirect {
        enable host
        resolver localhost:53
      }
      prometheus
      log / stdout "{remote} - [{when_iso}] \"{method} {uri} {proto}\" {status} {size} {latency}"
      errors
    }
    # TXTDirect -> slowdown
    :8003 {
      tls off
      txtdirect {
        enable host
        resolver localhost:54
      }
      prometheus
      log / stdout "{remote} - [{when_iso}] \"{method} {uri} {proto}\" {status} {size} {latency}"
      errors
    }
    :80/healthz {
      tls off
      status 200 /
    }
    :80/probez {
      tls off
      status 200 /
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: txtdirect-no-cache-tcp-k8s
  namespace: kubecon
  labels:
    project: txtdirect.io
    subproject: redirect
    component: appserver
    app: txtdirect
data:
  Corefile: |
    .:53 {
        errors
        health
        prometheus :9153
        proxy . -DNSIP- {
          protocol dns force_tcp
        }
      }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: txtdirect-cache-tcp-k8s
  namespace: kubecon
  labels:
    project: txtdirect.io
    subproject: redirect
    component: appserver
    app: txtdirect
data:
  Corefile: |
    .:53 {
        errors
        health
        prometheus :9153
        proxy . -DNSIP- {
          protocol dns force_tcp
        }
        cache 30
      }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: txtdirect-cache-grpc-local
  namespace: kubecon
  labels:
    project: txtdirect.io
    subproject: redirect
    component: appserver
    app: txtdirect
data:
  Corefile: |
    .:53 {
        errors
        health
        prometheus :9153
        proxy . -DNSIP- {
          protocol grpc insecure
        }
      }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: txtdirect-no-cache-tcp-local
  namespace: kubecon
  labels:
    project: txtdirect.io
    subproject: redirect
    component: appserver
    app: txtdirect
data:
  Corefile: |
    .:53 {
        errors
        health
        prometheus :9153
        proxy . /etc/resolv.conf
      }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: txtdirect-cache-tcp-local
  namespace: kubecon
  labels:
    project: txtdirect.io
    subproject: redirect
    component: appserver
    app: txtdirect
data:
  Corefile: |
    .:53 {
        errors
        health
        prometheus :9153
        proxy . /etc/resolv.conf
      }
