apiVersion: batch/v1
kind: Job
metadata:
  name: sendreq
  namespace: kubecon
spec:
  completions: 100
  parallelism: 100
  template:
    spec:
      containers:
      - name: sendreq
        image: gcr.io/kubecon-223920/sendreq:dev-9f8a11
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
        command: [ "sh", "-c", "./sendreq --hosts hosts.txt --endpoint http://10.55.246.158:8080 --parallel=false --iteration 1" ]
      restartPolicy: Never
