apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kubecon
data:
  Corefile: |
    .:53 {
      log
      errors
      health
      prometheus :9153
      proxy . /etc/resolv.conf
      cache 30
       loadbalance
    }