apiVersion: v1
kind: ConfigMap
metadata:
  name: ds-no-cache-tcp-k8s
  namespace: kubecon
  labels:
    app: txtdirect
data:
  Corefile: |
    .:53 {
        errors
        health
        prometheus :9153
        forward . 10.55.240.23 {
          force_tcp
        }
      }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ds-cache-tcp-k8s
  namespace: kubecon
  labels:
    app: txtdirect
data:
  Corefile: |
    .:53 {
      errors
      health
      prometheus :9153
      forward . 10.55.240.23 {
        force_tcp
      }
      cache 30
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: txtdirect-no-cache-grpc-k8s
  namespace: kubecon
  labels:
    project: txtdirect.io
    subproject: redirect
    component: appserver
    app: txtdirect
data:
  Corefile: |
    .:53 {
      errors
      health
      prometheus :9153
      proxy . 10.55.240.23 {
        protocol grpc insecure
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: txtdirect-cache-grpc-k8s
  namespace: kubecon
  labels:
    project: txtdirect.io
    subproject: redirect
    component: appserver
    app: txtdirect
data:
  Corefile: |
    .:53 {
      errors
      health
      prometheus :9153
      proxy . 10.55.240.23 {
        protocol grpc insecure
      }
      cache 30
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ds-no-cache-tcp-8
  namespace: kubecon
  labels:
    app: txtdirect
data:
  Corefile: |
    .:53 {
        errors
        health
        prometheus :9153
        forward . 8.8.8.8 {
          force_tcp
        }
      }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ds-cache-tcp-8
  namespace: kubecon
  labels:
    app: txtdirect
data:
  Corefile: |
    .:53 {
      errors
      health
      prometheus :9153
      forward . 8.8.8.8 {
        force_tcp
      }
      cache 30
    }