apiVersion: v1
kind: Service
metadata:
  name: coredns-ds
  namespace: kubecon
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    app: coredns-ds
spec:
  selector:
    app: coredns-ds
  ClusterIP: -DNSIP-local-
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP